CREATE TABLE IF NOT EXISTS demandes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  date_demande DATE NOT NULL,
  intitule VARCHAR(255) NOT NULL,
  responsable VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  programme VARCHAR(255),
  type_action VARCHAR(100) NOT NULL,
  thematiques JSON,
  objectifs TEXT NOT NULL,
  description TEXT NOT NULL,
  publics_cibles JSON,
  date_action DATE NOT NULL,
  horaire TIME,
  lieu VARCHAR(255),
  besoins_humains INT NOT NULL DEFAULT 1,
  materiel TEXT NOT NULL,
  partenaires TEXT,
  statut ENUM('en attente', 'validee', 'annulee') NOT NULL DEFAULT 'en attente',
  commentaire_admin TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 